# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9080
  servlet:
    context-path: /jbos
#mybatis
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
spring:
  main:
    show-banner: false
  devtools:
    restart:
      #热部署生效
      enabled: false
      #设置重启的目录
      additional-paths: src/main/java
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    check-template-location: true
    charset: utf-8
    content-type: text/html
    cache: false
jbos:
  websecurity:
    shiro: true
    loginUrl: /auth/getLogin
    excludeUrlPatterns: /login.html,/auth/login,/ws/**
    sessionTimeout: 60
    enableCache: true
  webservice:
    cxf:
      urlMappings: /ws/*
logging:
  level:
     com.jbos.* : debug
